### ISSUE TITLE
Buttons Component

### ISSUE THREAD

**Issue by baesparza** [UTPL-Rank/UI-Components#6]
**Description**

Create components for buttons and its variants, based in the material design specifications

**Tasks**

- [x] Support button style to buttons:`<button>` and anchor:`<a>` tags
- [x] Support base, primary color, warn, danger variant

---

Text Button

- [x] class name `btn`
- [x] Support enabled state or default state
- [x] Support hovered state
- [x] Support focused state
- [ ] Support pressed **This will be added in the future**
- [x] Support disabled state

---

Outlined

- [x] class name `btn-outlined`
- [x] Support enabled state or default state
- [x] Support hovered state
- [x] Support focused state
- [ ] Support pressed **This will be added in the future**
- [x] Support disabled state

---

Contained 

- [x] class name `btn-contained`
- [x] Support enabled state or default state
- [x] Support hovered state
- [x] Support focused state
- [ ] Support pressed **This will be added in the future**
- [x] Support disabled state

**Context**

- Don`t support buttons with icons
- Don't support toggle button

**Comment by baesparza** [comment]
```css
.button {
    color: green;
}
```
