### ISSUE TITLE
FAB Components 

### ISSUE THREAD

**Issue by baesparza** [UTPL-Rank/UI-Components#8]
**Description**

Create material component that implemente the material floating, action buttons

**❗ Note**: Use emojis instead of icons until the icons lib is ready

**Tasks**

- [x] Support butt on style to buttons:`<button>` and anchor:`<a>` tags
- [x] Support primary color, accent, warn, danger variant

---

FAB
 
- [x] Class name `fab`
- [x] Support resting as a default state
- [x] Support hovered state
- [x] Support focused state
- [ ] Support pressed **This will be added in the future**

---

FAB Mini
 
- [x] Class name `fab-mini `
- [x] Support resting as a default state
- [x] Support hovered state
- [x] Support focused state
- [ ] Support pressed **This will be added in the future**

---

FAB extended
  
- [x] Class name `fab-extended`
- [x] Support resting as a default state
- [x] Support hovered state
- [x] Support focused state
- [ ] Support pressed **This will be added in the future**

**Comment by baesparza** [comment]
Great Job
